### ISSUE TITLE
about Map

### ISSUE THREAD

**Issue by hygxmm** [RafaelBarbosatec/bonfire#240]
How can I seamlessly switch map without routing

**Comment by KyleKun** [comment]
Interesting question, I think it's possible to change all tiles in the current map but not sure if it's smooth... @RafaelBarbosatec do you think it's possible?

**Comment by DevNico** [comment]
Are there any plans to implement performant quick map switching?

**Comment by RafaelBarbosatec** [comment]
In the current way of changing maps, changing widgets is much more useful than updating the current game. Because if you do, you will lose everything from the previous state.
Currently, we have a satisfactory result.
Take a look this example: https://bonfire-engine.github.io/#/examples?id=multi-biome
