### ISSUE TITLE
有无限地图动态加载方法吗？

### ISSUE THREAD

**Issue by simanlx** [RafaelBarbosatec/bonfire#362]
有无限地图动态加载方法吗？

**Comment by RafaelBarbosatec** [comment]
Hi @simanlx !
Thanks for contacting !
There is a way to create dynamics maps using matrix (https://bonfire-engine.github.io/#/map?id=creating-map-by-matrix), and it’s possible load maps created by Tiled using url, just pass. the url instead of path in `WorldMapByTiled`.

But infinity maps dynamically is not possible yet. It’s a good idea ! I'll think about how adds this feature in the Bonfire.

**Comment by simanlx** [comment]
[](https://pic1.cdncl.net/user/Fermath/common_pic/6b9ebd48495a7926d700e11413ee646f.gif)

**Comment by simanlx** [comment]
[https://pic1.cdncl.net/user/Fermath/common_pic/6b9ebd48495a7926d700e11413ee646f.gif](url)

**Comment by simanlx** [comment]
https://pic1.cdncl.net/user/Fermath/common_pic/6b9ebd48495a7926d700e11413ee646f.gif

**Comment by RafaelBarbosatec** [comment]
Cool, the Bonfire do it to render just the necessary
If you want create a platform game. I recommend you use only Flame to do it.
